name: QuestSys
version: ${project.version}
main: com.QuestSys.QuestSys
api-version: '1.21'
authors: [ sch ]
description: plugin for Welten 4 - questsys
commands:
  QuestSys:
    usage: /questsys
    permission: QuestSys